daemon off;

events {}

http {
    types {
        text/html                             html htm;
        text/css                              css;
        text/javascript                       js;
        application/json                      json;
        image/png                             png;
        image/jpeg                            jpg jpeg;
        image/gif                             gif;
        image/svg+xml                         svg;
        image/x-icon                          ico;
        font/woff                             woff;
        font/woff2                            woff2;
    }
    default_type  application/octet-stream;

    server {
        listen 8080;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        error_page 404 /index.html;
    }
}
